version: '3'
services:
    postgres:
      restart: always
      logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
      shm_size: 1g
      image: postgres:14.0-alpine
      ports:
        - "5432:5432"
      environment:
        - DEBUG=false
        - POSTGRES_USER=${PG_USER}
        - POSTGRES_PASSWORD=${PG_PASSWORD}
        - POSTGRES_DB=${PG_DATABASE}
      networks:
        - default
      volumes:
      # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
      # It means that every time the repository is modifying the data inside
      # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
      # You don't need to create the `db-data` folder. Docker Compose will do it for you.
      - ./.humus_postgres/:/var/lib/postgresql/data/